// Generated by CoffeeScript 1.10.0
(function() {
  var Cookie, FAKE_APP_URI, WebStorageCookieStore, tough;

  tough = require('tough-cookie');

  WebStorageCookieStore = require('tough-cookie-web-storage-store');

  Cookie = tough.Cookie;

  FAKE_APP_URI = 'https://yourdomain.heap/';

  (function(document) {
    var cookiejar, store;
    store = new WebStorageCookieStore(localStorage);
    cookiejar = new tough.CookieJar(store);
    document.__defineGetter__('cookie', function() {
      return cookiejar.getCookieStringSync(FAKE_APP_URI);
    });
    return document.__defineSetter__('cookie', function(s) {
      return cookiejar.setCookieSync(Cookie.parse(s, {
        loose: true
      }), FAKE_APP_URI);
    });
  })(document);

}).call(this);
